#!/bin/bash -i

# The main python script needs to be run as root
# To enable passwordless starting/stopping of the remote control, we must add the command to the sudoers file:
#     Edit the sudoers file with
#         sudo visudo -f /etc/sudoers.d/souk-remote-control
#     Add the following line:
#         casper ALL=(ALL:ALL) NOPASSWD: /home/casper/py3venv/bin/python -u ./remote_control_server.py
#     Exit visudo
# Now the following can be executed without being prompted for a password...


echo "Starting remote control script"

cd /home/casper/src/souk-remote-control/souk_remote_control_server/

sudo /home/casper/py3venv/bin/python -u ./remote_control_server.py

echo "Finished remote control script"


